--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA AUTHORIZATION "ESBDVLP";

CREATE TABLE "ESBDVLP"."WMB_BINARY_DATA" (
		"WMB_MSGKEY" VARCHAR2(100) NOT NULL,
		"DATA_TYPE" NUMBER NOT NULL,
		"ENCODING" VARCHAR2(50) NOT NULL,
		"DATA" CLOB
	)
	NOLOGGING;

CREATE TABLE "ESBDVLP"."WMB_EVENT_FIELDS" (
		"EVENT_TYPE_ID" NUMBER NOT NULL,
		"KEY_FLD_ID" NUMBER NOT NULL,
		"KEY_FLD_NAME" VARCHAR2(100),
		"KEY_FLD_DESC" VARCHAR2(100),
		"KEY_FLD_PATH" VARCHAR2(200)
	)
	NOLOGGING;

CREATE TABLE "ESBDVLP"."WMB_EVENT_TYPES" (
		"EVENT_TYPE_ID" NUMBER NOT NULL,
		"EVENT_NAME" VARCHAR2(100),
		"EVENT_DESCRIPTION" VARCHAR2(100)
	)
	NOLOGGING;

CREATE TABLE "ESBDVLP"."WMB_MSGS" (
		"WMB_MSGKEY" VARCHAR2(100) NOT NULL,
		"HAS_BITSTREAM" CHAR(1),
		"HAS_EXCEPTION" CHAR(1),
		"HAS_USERDATA" CHAR(1),
		"EVENT_TYPE" VARCHAR2(100),
		"EVENT_NAME" VARCHAR2(100),
		"EVENT_SRCADDR" VARCHAR2(100),
		"BROKER_NAME" VARCHAR2(100),
		"BROKER_UUID" VARCHAR2(100),
		"EXGRP_NAME" VARCHAR2(100),
		"EXGRP_UUID" VARCHAR2(100),
		"MSGFLOW_NAME" VARCHAR2(100),
		"MSGFLOW_UUID" VARCHAR2(100),
		"APPL_NAME" VARCHAR2(100),
		"APPL_UUID" VARCHAR2(100),
		"LIBRARY_NAME" VARCHAR2(100),
		"LIBRARY_UUID" VARCHAR2(100),
		"NODE_NAME" VARCHAR2(100),
		"NODE_TYPE" VARCHAR2(100),
		"DETAIL" VARCHAR2(100),
		"TERMINAL_NAME" VARCHAR2(100),
		"KEY_FLD_1_NM" VARCHAR2(100),
		"KEY_FLD_2_NM" VARCHAR2(100),
		"KEY_FLD_3_NM" VARCHAR2(100),
		"KEY_FLD_4_NM" VARCHAR2(100),
		"KEY_FLD_5_NM" VARCHAR2(100),
		"EVENT_TIMESTAMP" VARCHAR2(100),
		"LOCAL_TRANSACTION_ID" VARCHAR2(100),
		"PARENT_TRANSACTION_ID" VARCHAR2(100),
		"GLOBAL_TRANSACTION_ID" VARCHAR2(100)
	)
	NOLOGGING;

ALTER TABLE "ESBDVLP"."WMB_BINARY_DATA" ADD CONSTRAINT "SYS_C0011062" CHECK ("WMB_MSGKEY" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_BINARY_DATA" ADD CONSTRAINT "SYS_C0011063" CHECK ("DATA_TYPE" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_BINARY_DATA" ADD CONSTRAINT "SYS_C0011064" CHECK ("ENCODING" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_BINARY_DATA" ADD CONSTRAINT "SYS_C0011065" PRIMARY KEY
	("WMB_MSGKEY",
	 "DATA_TYPE");

ALTER TABLE "ESBDVLP"."WMB_EVENT_FIELDS" ADD CONSTRAINT "SYS_C0011059" CHECK ("EVENT_TYPE_ID" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_EVENT_FIELDS" ADD CONSTRAINT "SYS_C0011060" CHECK ("KEY_FLD_ID" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_EVENT_FIELDS" ADD CONSTRAINT "SYS_C0011061" PRIMARY KEY
	("EVENT_TYPE_ID");

ALTER TABLE "ESBDVLP"."WMB_EVENT_TYPES" ADD CONSTRAINT "SYS_C0011057" CHECK ("EVENT_TYPE_ID" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_EVENT_TYPES" ADD CONSTRAINT "SYS_C0011058" PRIMARY KEY
	("EVENT_TYPE_ID");

ALTER TABLE "ESBDVLP"."WMB_MSGS" ADD CONSTRAINT "SYS_C0011055" CHECK ("WMB_MSGKEY" IS NOT NULL);

ALTER TABLE "ESBDVLP"."WMB_MSGS" ADD CONSTRAINT "SYS_C0011056" PRIMARY KEY
	("WMB_MSGKEY");

